apiVersion: v1
kind: ReplicationController
metadata:
  name: ph-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ph
    spec:
      imagePullSecrets:
        - name: harborsecret
      containers:
        - name: ph
          image: 192.168.149.20/java/spring-boot-demo-0.0.1-snapshot.jar:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          env:
            - name: key
              value: "value"
