apiVersion: v1
kind: Service
metadata:
  name: ph-service
spec:
  type: NodePort
  ports:
  - name: ph
    port: 8081
    nodePort: 31111
    targetPort: 8081
    protocol: TCP
  selector:
    app: ph
